/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_effectv_android_MainApplication */

#ifndef _Included_jp_effectv_android_MainApplication
#define _Included_jp_effectv_android_MainApplication
#ifdef __cplusplus
extern "C" {
#endif
#undef jp_effectv_android_MainApplication_DEBUG
#define jp_effectv_android_MainApplication_DEBUG 0L
#undef jp_effectv_android_MainApplication_DST_MSG_LEN
#define jp_effectv_android_MainApplication_DST_MSG_LEN 256L
/*
 * Class:     jp_effectv_android_MainApplication
 * Method:    native_init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_effectv_android_MainApplication_native_1init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_effectv_android_MainApplication
 * Method:    native_names
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jp_effectv_android_MainApplication_native_1names
  (JNIEnv *, jclass);

/*
 * Class:     jp_effectv_android_MainApplication
 * Method:    native_titles
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jp_effectv_android_MainApplication_native_1titles
  (JNIEnv *, jclass);

/*
 * Class:     jp_effectv_android_MainApplication
 * Method:    native_funcs
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jp_effectv_android_MainApplication_native_1funcs
  (JNIEnv *, jclass, jint);

/*
 * Class:     jp_effectv_android_MainApplication
 * Method:    native_start
 * Signature: (ZIIII)I
 */
JNIEXPORT jint JNICALL Java_jp_effectv_android_MainApplication_native_1start
  (JNIEnv *, jclass, jboolean, jint, jint, jint, jint);

/*
 * Class:     jp_effectv_android_MainApplication
 * Method:    native_stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_effectv_android_MainApplication_native_1stop
  (JNIEnv *, jclass);

/*
 * Class:     jp_effectv_android_MainApplication
 * Method:    native_draw
 * Signature: ([B[I[CI[B)I
 */
JNIEXPORT jint JNICALL Java_jp_effectv_android_MainApplication_native_1draw
  (JNIEnv *, jclass, jbyteArray, jintArray, jcharArray, jint, jbyteArray);

/*
 * Class:     jp_effectv_android_MainApplication
 * Method:    native_event
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_effectv_android_MainApplication_native_1event
  (JNIEnv *, jclass, jint);

/*
 * Class:     jp_effectv_android_MainApplication
 * Method:    native_touch
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_jp_effectv_android_MainApplication_native_1touch
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     jp_effectv_android_MainApplication
 * Method:    native_cnvavc
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_effectv_android_MainApplication_native_1cnvavc
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
